### ISSUE TITLE
BUG: plugin stops PmPro setting BP member type for new users

### ISSUE THREAD

**Issue by delahoc** [strangerstudios/pmpro-email-confirmation#29] opened 2019-11-05 23:37 UTC
With this email-confirmation plugin disabled, my PmPro sets the BuddyPress Membership type as it should, according to the options settings I've created. However, with the email-confirmation plugin enabled, PmPro no longer sets the BuddyPress Membership type. 

Are you aware of this bug? Do you have a fix?

**Comment by grifini** [comment] 2020-02-26 13:24
I have a similar problem here as well. No priorly defined access restriction works Until the email confirmation by the user. Hence, users can use any buddypress feature without any restriction if they don't confirm their account. Is there any solution for this?

**Comment by andrewlimaza** [comment] 2020-09-07 10:06
@grifini I am running some tests with BuddyPress now. The Email Confirmation will give the user a membership level but should restrict access.

When you refer to the user being able to use any feature, does this mean they may access restricted content while awaiting validation? There's another ticket that says it redirects user's to the Access Restricted page until they are validated. (https://github.com/strangerstudios/pmpro-email-confirmation/issues/36)

@delahoc, I'll revert back as soon as I possibly can.

**Comment by andrewlimaza** [comment] 2020-09-07 10:46
@grifini - I've just tested this, user's that have not validated their email should get redirected to the 'Access Restricted'.

**Comment by andrewlimaza** [comment] 2020-09-07 10:52
@delahoc I've just tested this and it does work as intended, the user is assigned to a Membership Type inside BuddyPress.

I've followed this guide - https://www.paidmembershipspro.com/apply-a-buddypress-member-type-on-membership-checkout-or-level-change/

Please see the Member Type here:

![Screen Shot 2020-09-07 at 12 51 15](https://user-images.githubusercontent.com/12629136/92380140-e909fe00-f108-11ea-948a-fff6fa0f75d0.png)

**Comment by andrewlimaza** [comment] 2020-09-07 10:53
If this is still not working for you, please open a support ticket on www.paidmembershipspro.com and someone from our team will assist you further.

**Closed** 2020-09-07 10:53 UTC
